name: Bug report
description: Report a broken link, rendering issue, or incorrect content
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: url
    attributes:
      label: Page URL
      placeholder: https://precice.org/some-page.html
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What is wrong?
      placeholder: "The link to X returns a 404. It should point to Y."
    validations:
      required: true
