name: Documentation improvement
description: Suggest an improvement or flag missing/unclear content
title: "[Docs]: "
labels: ["content"]
body:
  - type: input
    id: url
    attributes:
      label: Page URL (if applicable)
      placeholder: https://precice.org/some-page.html
  - type: textarea
    id: description
    attributes:
      label: What should be improved?
      placeholder: "The section on X doesn't explain Y..."
    validations:
      required: true
